# Generated by Django 3.0.5 on 2020-05-26 06:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Current',
            fields=[
                ('id', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=20, unique=True, verbose_name='名称')),
            ],
            options={
                'verbose_name': '管理流动资产',
                'verbose_name_plural': '管理流动资产',
            },
        ),
    ]
