# Generated by Django 3.0.5 on 2020-05-26 06:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('place', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Fixed',
            fields=[
                ('id', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=20, unique=True, verbose_name='名称')),
                ('status', models.CharField(choices=[('using', '在用'), ('idle', '闲置'), ('broken', '损坏')], max_length=6, verbose_name='状态')),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='location', to='place.Room', to_field='name', verbose_name='位置')),
            ],
            options={
                'verbose_name': '管理固定资产',
                'verbose_name_plural': '管理固定资产',
            },
        ),
    ]
