# Generated by Django 3.0.5 on 2020-05-26 06:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=20, unique=True, verbose_name='名称')),
                ('function', models.CharField(choices=[('office', '办公室'), ('warehouse', '仓库')], max_length=10, verbose_name='用途')),
            ],
            options={
                'verbose_name': '管理办公室及仓库',
                'verbose_name_plural': '管理办公室及仓库',
            },
        ),
        migrations.CreateModel(
            name='Area',
            fields=[
                ('id', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=20, unique=True, verbose_name='名称')),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='room', to='place.Room', to_field='name', verbose_name='所在位置')),
            ],
            options={
                'verbose_name': '管理货架',
                'verbose_name_plural': '管理货架',
            },
        ),
    ]
