# Generated by Django 3.0.5 on 2020-05-26 06:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('place', '0001_initial'),
        ('current', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CurrentStorage',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('current_name', models.CharField(max_length=20, verbose_name='物资名称')),
                ('room_name', models.CharField(max_length=20, verbose_name='所在房间')),
                ('area_name', models.CharField(max_length=20, verbose_name='所在位置')),
                ('quantity', models.IntegerField(verbose_name='库存数量')),
            ],
            options={
                'verbose_name': '流动资产库存',
                'verbose_name_plural': '流动资产库存',
            },
        ),
        migrations.CreateModel(
            name='CurrentRecord',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('quantity', models.IntegerField(verbose_name='数量')),
                ('in_out', models.CharField(choices=[('in', '入库'), ('out', '出库')], max_length=6, verbose_name='出入库')),
                ('operation_datetime', models.DateTimeField(auto_now=True, verbose_name='操作时间')),
                ('operation_username', models.CharField(max_length=16, verbose_name='操作人')),
                ('comment', models.TextField(blank=True, max_length=200, verbose_name='备注')),
                ('area_name', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='area_name', to='place.Area', to_field='name', verbose_name='所在位置')),
                ('current_name', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='current_name', to='current.Current', to_field='name', verbose_name='名称')),
            ],
            options={
                'verbose_name': '流动资产入出库记录',
                'verbose_name_plural': '流动资产入出库记录',
            },
        ),
    ]
